### PR TITLE
fix: init countly at page load & track initial pageview

### LINKED ISSUE #207: Missing Analytics for docs
We are missing analytics in countly for docs since Octobe 26. Maybe related to docosaurus switch?

### PR DESCRIPTION
**Pull request by yusefnapora**
This changes the way we load the countly SDK.

Quick recap of how the countly integration works, since I don't think it's documented well elsewhere. 

Basically, to hook into docusaurus's router and get notified on route changes, I had to write a custom docusaurus plugin and use the `onRouteUpdate` hook (described in this [SO answer](https://stackoverflow.com/a/63981821/1292992)). Unfortunately, it seems this hook doesn't fire for the initial page load.

This changes the plugin to initialize the countly sdk in a script tag that gets injected into every page - because this script executes at the global scope and can't `import` stuff from the bundle, it loads the countly SDK from a CDN into the global `window.Countly` object instead of importing the npm package.

I tested locally with `COUNTLY_KEY=<production-key> DEBUG_ENABLE_COUNTLY=true npm run start` and get what looks like success:

Screen Shot 2021-11-15 at 1 26 59 PM

Closes #207

### CODE REVIEW

File: src/util/countly.js [hunk 1]
```diff
@@ -14,36 +12,12 @@ export const events = {
...
 
-  if (!window._countlyConfig) {
-    if (!warnedAboutMissingCountly) {
-      console.warn('no countly configuration found. analytics disabled')
-      warnedAboutMissingCountly = true
-    }
-    return
-  }
-
-  const { appKey, url } = window._countlyConfig
```
Comment (yusefnapora) [inline src/util/countly.js:31]: I'm pretty sure this is the reason we weren't getting any events (we should have been at least getting click events, just not the initial pageview). The problem is that the `window._countlyConfig` actually has a `countlyUrl` field, not `url` so it was always initializing the sdk with an `undefined` URL 🤦

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Docusaurus build was successful!
- No markdown files were changed, so no page checks were run!
